@echo off
setlocal
chcp 65001 >nul

title Tapo Monitor - 자동 시작 등록

REM 이 배치 파일이 위치한 tapo-monitor 폴더를 프로젝트 루트로 간주
cd /d "%~dp0"
set "PROJECT_DIR=%CD%"
set "TASK_NAME=TapoMonitor"
set "VBS_WRAPPER=%PROJECT_DIR%\run-tapo-monitor.vbs"

echo ==========================================================
echo   Tapo Monitor - Windows 자동 시작 등록
echo ==========================================================
echo.
echo   프로젝트 폴더 : %PROJECT_DIR%
echo   작업 이름      : %TASK_NAME%
echo   실행 시점      : 현재 사용자 로그온 시 (Windows 로그인 직후)
echo.

REM ---------- 사전 점검: package.json 존재 확인 ----------
if not exist "package.json" (
    echo [오류] 현재 폴더에 package.json 이 없습니다.
    echo        이 스크립트는 tapo-monitor 폴더 안에서 실행해야 합니다.
    echo.
    pause
    exit /b 1
)

REM ---------- VBS 래퍼 생성 (콘솔 창 없이 실행) ----------
REM Task Scheduler 가 직접 cmd 를 띄우면 검은 창이 깜빡이므로
REM VBS 로 감싸서 hidden 실행한다.
echo [1/2] 백그라운드 실행용 래퍼 생성...
(
    echo ' Auto-generated by setup-autostart.bat -- do not edit.
    echo Set WshShell = CreateObject^("WScript.Shell"^)
    echo WshShell.CurrentDirectory = "%PROJECT_DIR%"
    echo WshShell.Run "cmd /c npm start", 0, False
) > "%VBS_WRAPPER%"
if not exist "%VBS_WRAPPER%" (
    echo [오류] 래퍼 파일 생성 실패.
    pause
    exit /b 1
)

REM ---------- schtasks 등록 ----------
echo [2/2] Windows Task Scheduler 에 등록...
schtasks /Create /F ^
    /TN "%TASK_NAME%" ^
    /TR "wscript.exe \"%VBS_WRAPPER%\"" ^
    /SC ONLOGON ^
    /RL LIMITED
if errorlevel 1 (
    echo.
    echo [오류] 작업 등록 실패.
    pause
    exit /b 1
)

echo.
echo ==========================================================
echo   등록이 완료되었습니다.
echo ==========================================================
echo.
echo   - 다음 Windows 로그온부터 tapo-monitor 가 자동 실행됩니다.
echo   - 로그 파일: %PROJECT_DIR%\tapo-monitor.log (필요 시 index.ts 에서 추가)
echo.
echo   즉시 실행하려면:
echo     schtasks /Run /TN "%TASK_NAME%"
echo.
echo   실행 중 확인:
echo     schtasks /Query /TN "%TASK_NAME%" /V /FO LIST
echo.
echo   자동 시작 해제:
echo     이 폴더의 uninstall-autostart.bat 실행
echo.
pause
endlocal
